### PR TITLE
24-utilized the public folder instead of the app assets folder...

### PR DESCRIPTION
**Pull request by hardyoyo**
... to serve the ucla-banner.jpg file, revised the banner configuration to match

### CODE REVIEW

**Comment by hardyoyo** [comment]
issue: https://github.com/UCLALibrary/samvera-mgmt/issues/24

**Comment by bess** [comment]
@ksclarke Are you asking for changes with your review? If so, would you specifically mark this "Changes Requested"? It helps keep things moving through more quickly if it's unambiguous whether you're asking for changes or whether this is just a passing comment.

**Comment by ksclarke** [comment]
I'm not asking for changes. Just raising the question. If someone else reviews without asking for the change I'm fine.

**Comment by bess** [comment]
@ksclarke Awesome, thanks for clarifying.

**Pull request merged**
