### PR TITLE
Simplify configs

### PR DESCRIPTION
**Pull request by ksclarke**
Use FEDORA_URL instead of FEDORA_HOST in configs
Use (SOLR_URL or FEDORA_URL) or a default fixed value in configs

### CODE REVIEW

**Comment by sgurnick** [comment]
I noticed that some of the config changes suggested in this PR will cause a divergence from how my ansible role set-up variables. We should go through this first so we can all agree on what changes need to be made across the board.

**Comment by ksclarke** [comment]
@sgurnick Does "go through this first" mean merge the above or discuss the above?

**Comment by sgurnick** [comment]
@ksclarke I was suggesting that we discuss first to ensure we capture all the changes so I can make the corresponding adjustments in the ansible roles.

**Comment by ksclarke** [comment]
@sgurnick Are you suggesting this change needs a meeting or can the discussion happen here?

**Comment by sgurnick** [comment]
I believe it's something that should occur during one of our DevOps meetings so we can ensure everything is on-board with changes.

**Comment by no-reply** [comment]
@sgurnick, @ksclarke. After working on this a bit today, I don't think these changes actually reflect a change from what is deploying to production for the Red Hat environment. Compare to #90.

The differences I see are all isolated to the `development` and `test` environments. The changes to `production`, here seem to be in the direction of what's required by the new ansible roles.

Unless I'm missing something(?), I'd propose to merge this and rebase #90 on top of it.

**Comment by sgurnick** [comment]
@no-reply that sounds good to me.

**Pull request merged**
