### PR TITLE
Enable deloyment via the UCLA Jump Server

### PR DESCRIPTION
**Pull request by sgurnick**
The purpose of this branch is to introduce configuration in the `deploy.rb` file to allow deployment of code via the UCLA bastion host (`jump.library.ucla.edu`). 

This allows us to maintain secure server environments - keeping firewall access in place to limit direct access to our servers. 

This configuration creates a new environment variable `VIA_JUMP` that allows the entity deploying the code to set whether or not code is deployed through the jump server or directly to the server environment.

### CODE REVIEW

**Comment by no-reply** [comment]
@sgurnick It looks like this branch is a bit behind `master`, and based on an older version of the MySQL work. Many of the commits are near duplicates of merged work.

Can we rebase it on `master`, or cherry pick the final two commits?

**Comment by sgurnick** [comment]
@no-reply: I'm good with just cherry picking the commits specific to the jump server deployment configuration. I'm curious how we do that and would love to "shoulder hover" whenever you have some time.

**Comment by no-reply** [comment]
Sure thing! how does after standup sound?

**Comment by sgurnick** [comment]
@no-reply That would be great.

**Pull request closed without merging**
